create table address (id bigint not null auto_increment, apartment integer, building integer, city varchar(255), special_marque varchar(255), state varchar(255), street_details varchar(255), user_id bigint, primary key (id)) engine=InnoDB;
create table admin (user_id bigint not null, primary key (user_id)) engine=InnoDB;
create table cart (id bigint not null auto_increment, last_update date, customer_id bigint, primary key (id)) engine=InnoDB;
create table cart_item (id bigint not null auto_increment, quantity integer, product_id bigint, cart_id bigint, primary key (id)) engine=InnoDB;
create table category (id bigint not null auto_increment, description varchar(255), image_url varchar(255), name varchar(255), main_category bigint, primary key (id)) engine=InnoDB;
create table customer (type integer not null, user_id bigint not null, primary key (user_id)) engine=InnoDB;
create table grade (id bigint not null auto_increment, grade_number integer, grade_level bigint, primary key (id)) engine=InnoDB;
create table grade_level (id bigint not null auto_increment, level varchar(255), primary key (id)) engine=InnoDB;
create table offers (id bigint not null auto_increment, discount double precision, end_date datetime, start_date datetime, product_id bigint, primary key (id)) engine=InnoDB;
create table order_details (id bigint not null auto_increment, address_id bigint, customer_id bigint, order_id bigint, shipper_id bigint, primary key (id)) engine=InnoDB;
create table order_item (id bigint not null auto_increment, price_per_unit double precision, quantity integer, order_id bigint, product_id bigint, primary key (id)) engine=InnoDB;
create table order_status (id bigint not null auto_increment, status_date date, stage_value integer not null, order_id bigint, primary key (id)) engine=InnoDB;
create table orders (id bigint not null auto_increment, primary key (id)) engine=InnoDB;
create table package (id bigint not null auto_increment, quantity integer, grade_id bigint, product_id bigint, primary key (id)) engine=InnoDB;
create table product (id bigint not null auto_increment, description varchar(255), in_stock integer not null, min_stock integer, price integer not null, name varchar(255), category_id bigint, primary key (id)) engine=InnoDB;
create table product_images (id bigint not null auto_increment, image_url varchar(255), is_main integer default 1 not null, product_id bigint, primary key (id)) engine=InnoDB;
create table product_patch (id bigint not null auto_increment, date_in date, purchasing_price double precision, quantity integer, admin_id bigint, product_id bigint, primary key (id)) engine=InnoDB;
create table shipper (status bit, name varchar(255), shipping_fees double precision, user_id bigint not null, primary key (user_id)) engine=InnoDB;
create table user (id bigint not null auto_increment, created date, email varchar(255), first_name varchar(255), is_enabled integer not null, last_name varchar(255), password varchar(255), phone_number1 varchar(255), phone_number2 varchar(255), user_type_id bigint, primary key (id)) engine=InnoDB;
create table user_type (id bigint not null auto_increment, type varchar(255), primary key (id)) engine=InnoDB;
alter table user add constraint UK_ob8kqyqqgmefl0aco34akdtpe unique (email);
alter table address add constraint FKda8tuywtf0gb6sedwk7la1pgi foreign key (user_id) references user (id);
alter table admin add constraint FK8ahhk8vqegfrt6pd1p9i03aej foreign key (user_id) references user (id);
alter table cart add constraint FKdebwvad6pp1ekiqy5jtixqbaj foreign key (customer_id) references customer (user_id);
alter table cart_item add constraint FKjcyd5wv4igqnw413rgxbfu4nv foreign key (product_id) references product (id);
alter table cart_item add constraint FK1uobyhgl1wvgt1jpccia8xxs3 foreign key (cart_id) references cart (id);
alter table category add constraint FKnerogmy74kcwjcjoa2xof9xyp foreign key (main_category) references category (id);
alter table customer add constraint FKj8dlm21j202cadsbfkoem0s58 foreign key (user_id) references user (id);
alter table grade add constraint FKt9ng6d43us6n47ha3r3cj8l6f foreign key (grade_level) references grade_level (id);
alter table offers add constraint FKr6laelux55x74wkku2jn3krt3 foreign key (product_id) references product (id);
alter table order_details add constraint FK27vqmwve30hvoewnwtxyjnx4g foreign key (address_id) references address (id);
alter table order_details add constraint FK3x5l78p8fkdgbqgt1ta6ro5lm foreign key (customer_id) references customer (user_id);
alter table order_details add constraint FKjyu2qbqt8gnvno9oe9j2s2ldk foreign key (order_id) references orders (id);
alter table order_details add constraint FKfo90182l2ous9g30h3rjkl7s2 foreign key (shipper_id) references shipper (user_id);
alter table order_item add constraint FKt4dc2r9nbvbujrljv3e23iibt foreign key (order_id) references orders (id);
alter table order_item add constraint FK551losx9j75ss5d6bfsqvijna foreign key (product_id) references product (id);
alter table order_status add constraint FK48efngdcgl1e9tkfbcalk35gl foreign key (order_id) references orders (id);
alter table package add constraint FKle2ou718xiqb5pouop9jdnp3o foreign key (grade_id) references grade (id);
alter table package add constraint FKinuhpqerd49iykyqmpqjn5w31 foreign key (product_id) references product (id);
alter table product add constraint FK1mtsbur82frn64de7balymq9s foreign key (category_id) references category (id);
alter table product_images add constraint FKi8jnqq05sk5nkma3pfp3ylqrt foreign key (product_id) references product (id);
alter table product_patch add constraint FKbb11wrfi12y8aqm8t959pkpv4 foreign key (admin_id) references admin (user_id);
alter table product_patch add constraint FK5rvussdc7aofr4s2hy6xmv0fc foreign key (product_id) references product (id);
alter table shipper add constraint FKe1pqdhq5ffxlc6hny0o2wncda foreign key (user_id) references user (id);
alter table user add constraint FKlrk9xrdps0emd6d5rx5x3ib6h foreign key (user_type_id) references user_type (id);
